---
version: "3.8"

services:
  db:
    image: postgres:16-alpine

    environment:
      POSTGRES_USER: user
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password

    ports:
      - 127.0.0.1:5432:5432

  redis:
    image: redis:7-alpine

    ports:
      - 127.0.0.1:6379:6379

